//
//  Constants.m
//  Demo
//
//  Created by Will on 09/10/2016.
//  Copyright © 2016 Will. All rights reserved.
//

#import "Constants.h"

@implementation Constants

//db
NSString *const USER_REVIEW_TABLE_CREATOR = @"CREATE TABLE IF NOT EXISTS USERREVIEWS (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME_OF_LOCATION TEXT, REVIEW_SCORE INTEGER)";

NSString *const USER_FAVE_TABLE_CREATOR = @"CREATE TABLE IF NOT EXISTS FAVEPLACES (ID INTEGER PRIMARY KEY AUTOINCREMENT, GOOGLE_PLACE_ID TEXT, NAME TEXT, PHONE_NUMBER TEXT, RATING REAL, WEBSITE TEXT)";

NSString *const TWITTER_TOKEN_MATCH_REGEX = @"(:\\)|:\\(|=\\)|=\\(|:\\[|:\\]|:-\\)|:-\\()|[A-Za-z]+";

NSString* const PLACE_INSERT_STR = @"INSERT INTO FAVE_PLACES (PLACE_ID, NAME, PHONE, WEBSITE, ADDRESS, COMMENTS) VALUES ('%@','%@','%@','%@','%@', '%@')";

NSString* const PLACE_UPDATE_STR = @"UPDATE FAVE_PLACES SET NAME ='%@', PHONE = '%@', WEBSITE = '%@', ADDRESS = '%@', COMMENTS = '%@' WHERE PLACE_ID = '%@'";

NSString* const FAVE_PLACES_TABLE = @"CREATE TABLE IF NOT EXISTS FAVE_PLACES (ID INTEGER PRIMARY KEY AUTOINCREMENT, PLACE_ID TEXT, ADDRESS TEXT, PHONE TEXT, COMMENTS TEXT, NAME TEXT, WEBSITE TEXT)";

NSString* const IMAGE_LINK_TABLE = @"CREATE TABLE IF NOT EXISTS IMAGE_LINKS (ID INTEGER PRIMARY KEY AUTOINCREMENT, PATH TEXT, PLACE_ID TEXT, FOREIGN KEY(PLACE_ID) REFERENCES FAVE_PLACES(PLACE_ID), UNIQUE(PATH, PLACE_ID))";

NSString* const HIGHSCORES_TABLE = @"CREATE TABLE IF NOT EXISTS HIGHSCORES (ID INTEGER PRIMARY KEY AUTOINCREMENT, NAME TEXT, SCORE TEXT, GAME_EMOTION TEXT, WAVE TEXT)";

NSString* const IMAGE_LINKS_FOR_PLACE_ID = @"SELECT * FROM IMAGE_LINKS WHERE PLACE_ID = '%@'";

NSString* const IMAGE_LINKS_INSERT_STR = @"INSERT OR IGNORE INTO IMAGE_LINKS (PATH, PLACE_ID) VALUES ('%1$@', '%2$@')";

NSString* const HIGHSCORE_INSERT_STR = @"INSERT INTO HIGHSCORES (NAME, SCORE, GAME_EMOTION, WAVE) VALUES ('%1$@', '%2$@', '%3$@', '%4$@')";

//Sentiment analysis constants
double const PRIOR_POSITIVE_COUNT_TWITTER = 790185;
double const PRIOR_NEGATIVE_COUNT_TWITTER = 788442;

int const TWEET_AMOUNT = 100;
int const RADIUS_FOR_TWEETS = 100;

//img files
NSString* const BACKGROUND_IMG = @"miCity_bg.png";

NSString* const TWITTER_IMG_1 = @"tweet_1.png";
NSString* const TWITTER_IMG_2 = @"tweet_2.png";
NSString* const TWITTER_IMG_3 = @"tweet_3.png";
NSString* const TWITTER_IMG_4 = @"tweet_4.png";

//headers
NSString* const USER_HEADER = @"User";
NSString* const TWEET_HEADER = @"Tweet";

//Db columns
NSString* const PLACE_ID = @"PLACE_ID";
NSString* const ADDRESS = @"ADDRESS";
NSString* const PATH = @"PATH";
NSString* const PATHS = @"PATHS";
NSString* const WEBSITE = @"WEBSITE";
NSString* const NAME = @"NAME";
NSString* const PHONE = @"PHONE";
NSString* const COMMENTS = @"COMMENTS";

double const POLARITY_THRESH_HOLD = 0.05;

@end
